### ISSUE TITLE
How to use this API in windows 10

### ISSUE THREAD

**Issue by MMalikKhan** [amplitude/amplitude-win#1]
Hi, 

I have a windows 10 project targeting mobile and desktops and laptops. i want to use Amplitude. I downloaded the project but i am lost how i can use this in my project. Is there a nuget package which i can reference as a dependency in my project and use it? I could not compile and make it work in my local. could you please let me know what i am missing. should add the whole project to my solution? or just the compiled dll for win 10 work, thanks

**Comment by djih** [comment]
Hi @MMalikKhan, unfortunately this SDK was built for windows phone, and hasn't been tested for Windows 10. It's likely that Windows 10 is unsupported at this time.
